//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoWeb
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Empleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleados()
        {
            this.Transacciones = new HashSet<Transacciones>();
        }
        

        public int IdEmpleado { get; set; }
        public string Cedula { get; set; }
        public string Nombre { get; set; }
        [Display(Name = "Departamento")]
        public int IdDepartamento { get; set; }
        [Display(Name = "Puesto")]
        public int IdPuesto { get; set; }
        [Range(1, int.MaxValue, ErrorMessage ="Este campo debe de ser mayor a cero")]
        [Display(Name = "Salario")]
        public int SalarioMensual { get; set; }
        [Display(Name = "Nomina")]
        public int IdNomina { get; set; }
        public bool Estado { get; set; }
    
        public virtual Departamentos Departamentos { get; set; }
        public virtual Puestos Puestos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transacciones> Transacciones { get; set; }
    }
}
