//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoWeb
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
   

    public partial class Puestos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Puestos()
        {
            this.Empleados = new HashSet<Empleados>();
        }

        public int IdPuesto { get; set; }
        [Display(Name = "Puesto")]
        public string NombrePuesto { get; set; }
        [Range(1, int.MaxValue, ErrorMessage = "Este campo debe de ser mayor que cero")]
        [Display(Name = "Nivel de Riesgo")]
        public int NivelRiesgo { get; set; }
        [Display(Name = "Salario Minimo")]
        [Range(1, int.MaxValue, ErrorMessage = "Este campo debe de ser mayor que cero")]
        public int NivelMinimoSalario { get; set; }
        [Range(1, int.MaxValue, ErrorMessage = "Este campo debe de ser mayor que cero")]
        [Display(Name = "Salario Maximo")]
        public int NivelMáximoSalario { get; set; }
        public bool Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleados> Empleados { get; set; }
    }
}
