//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoWeb
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Transacciones
    {
        public int IdTransaccion { get; set; }
        public int IdEmpleado { get; set; }
        public int IdIngreso { get; set; }
        public int IdDeduccion { get; set; }
        [Display(Name = "Tipo de Transaccion")]
        public string TipoTransaccion { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime Fecha { get; set; }
        [Range(1, int.MaxValue, ErrorMessage = "Este campo debe de ser mayor a cero")]
        public int Monto { get; set; }
        public bool Estado { get; set; }
    
        public virtual Deducciones Deducciones { get; set; }
        public virtual Empleados Empleados { get; set; }
        public virtual Ingreso Ingreso { get; set; }
    }
}
